### PR TITLE
Feature/slack handle

### PR DESCRIPTION
**Pull request by rouzbeh84**
not sure if this is consistent across all slack channels for everybody? 

made it say `usual` just in case

### CODE REVIEW

**Comment by ashwell** [comment]
@rouzbeh84 I think we want to ask specifically for their "jsla.slack.com" slack handle

**Comment by ashwell** [comment]
Maybe something like,

```
What is your js.la slack handle? Not a member? [Join here!](https://jsla-slackin.herokuapp.com/)
```

**Comment by rouzbeh84** [comment]
I like it! I'll update shortly.

**Comment by ashwell** [comment]
@rouzbeh84 so I haven't worked with choo yet but you may be able to just pass an HTML string as the label value...

something like:
```js
${textField({
  key: 'slack',
  label: html`What is your js.la slack handle? Not a member? <a href="https://jsla-slackin.herokuapp.com/" target="_blank">Join here!</a>`,
  placeholder: '@slackFace',
  value: speaker.slack
}, update)}
```

pinging resident choo guru @davidguttman

**Comment by davidguttman** [comment]
A Github notification!

@ashwell: don't see a reason why that wouldn't work

**Comment by rouzbeh84** [comment]
gotcha, i forgot that `html` prefix ha. will update soon

**Comment by ashwell** [comment]
@rouzbeh84 sorry but not sorry to be "that guy"

ummmm, excuse me but `html` is not a prefix, it is a `tag` since this is a [tagged template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals)

:trollface:

**Comment by rouzbeh84** [comment]
es bien?

**Pull request merged**
